services:
  - type: web
    name: doctor-recommendation-system
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PYTHONPATH
        value: src
    healthCheckPath: /
    autoDeploy: true