services:
  - type: web
    name: doctor-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app --bind=0.0.0.0:$PORT --workers=4 --timeout=120
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PYTHONPATH
        value: src
      - key: FLASK_ENV
        value: production