services:
  - type: web
    name: doctor-recommendation-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHONPATH
        value: src